fixed "doest not reflect rating count of c5j_rating_page when c5j_rat…
concrete5cojp/c5j_ratings pull request #4
Opened 2021-12-07 07:43 UTC by Hmone23

…ing_btn is clicked"

2021-12-07 23:59 UTC, biplobice requested changes
What's the reason for using `uID`?
It won't work if the user is not logged in.

2021-12-08 01:16 UTC, Hmone23 commented
@biplobice 

> What's the reason for using uID?

I used the UID because the C5j_ratings_btn block only shows the user's rating count.

> It won't work if the user is not logged in.

`getRatingsCount() is used in `view()`, please tell me how to fix for `view()`?

2021-12-08 09:11 UTC, biplobice commented
@Hmone23 
> I used the UID because the C5j_ratings_btn block only shows the user's rating count.

Nope, that's not true. It should show the rating of all users.

> getRatingsCount() is used in view(), please tell me how to fix for view()`?

You know, there is a client ID generated by the client.js if the user is not logged in.

2021-12-10 03:08 UTC, biplobice commented
@Hmone23 
Can you please explain the actual issue you're trying to fix?
The rating count seems working fine for me.

2021-12-10 04:55 UTC, Hmone23 commented
@biplobice 

>  If clicked the "Like" button in the c5j_page_list block, it is not be reflected in the c5j_rating_btn block.

I fixed the above issue.

2021-12-10 10:16 UTC, biplobice commented
I see.
We need to discuss this.
IMO, the rating button block shouldn't include the page list block's rating count.
**C5j Rating Button Block:** Should display the rating count of that block. i.e. - `getRatingCountByBlockID()`
**C5j Rating Pag List Block:** Should display the rating count by the page. i.e. - `getRatingCountByCollectionID()`

2021-12-13 06:19 UTC, biplobice commented
@Hmone23 

![Screen Shot 2021-12-13 at 3 14 43 PM](https://user-images.githubusercontent.com/2462951/145762111-b0e1f68f-3c65-4b30-972c-6d2f348fe6b0.png)

2021-12-13 09:44 UTC, Hmone23 commented
@biplobice 

It should change when the page is refreshed.
This will not work unless the page is refreshed.

2021-12-13 09:49 UTC, biplobice commented
@Hmone23 
It doesn't work even after the page refresh.

2021-12-13 10:41 UTC, Hmone23 commented
@biplobice 

> It doesn't work even after the page refresh.

It works fine in my local.
Please send me screen recording.

2021-12-14 04:40 UTC, biplobice commented
@Hmone23 
It happens only when you aren’t logged in.
Please check the screen recording.

https://user-images.githubusercontent.com/2462951/145934198-a5ff68fa-71b0-46cb-b74b-4b33979bf48b.mp4

2021-12-16 04:27 UTC, biplobice commented on blocks/c5j_rating_btn/controller.php
> +        $c = \Page::getCurrentPage();
@Hmone23 
Thanks. It's working now.
One more small request-
Aliases are deprecated. See https://documentation.concretecms.org/developers/appendix/deprecated-code-reference-ongoing
Please use `$this->getRequest()->getCurrentPage()` instead of `\Page::getCurrentPage();`

2021-12-16 04:49 UTC, Hmone23 commented
@biplobice 

> Please use $this->getRequest()->getCurrentPage() instead of \Page::getCurrentPage();

Fixed

2021-12-16 04:54 UTC, merged