update the package version and CHANGELOG
concrete5cojp/c5j_ratings pull request #8
Opened 2022-02-18 01:34 UTC by Hmone23

@biplobice 

> https://github.com/concrete5cojp/c5j_ratings/issues/2

I fixed above issue.
Please confirm PR.

2022-02-21 06:14 UTC, biplobice commented
@Hmone23 
1. It’s better to have the page path `/dashboard/rating_history` instead of `/dashboard/ratings_history`. I prefer `/dashboard/ratings`.
2. I think you know about `$autoSortColumns`. If not, please check-
- https://github.com/concrete5/concrete5/blob/85e56adc1516381b3d9cfdd66fc554fabac5b1a6/concrete/src/User/Point/EntryList.php#L12
- https://legacy-documentation.concrete5.org/developers/system/searching-sorting-paging
- https://notnil-creative.com/blog/archives/2565
3. Please follow concrete CMS conventions about naming. `src/Export/ExportRatings.php`
- https://github.com/concrete5/concrete5/blob/f49c756156caaa598749469e5727d0b2bf119a9f/concrete/src/Csv/Export/UserExporter.php
- https://github.com/concrete5/concrete5/blob/9d2f9432cb4746caa1a7ae45f4871a5efbf6b6ac/concrete/src/Express/Export/EntryList/CsvWriter.php

2022-02-22 01:44 UTC, Hmone23 commented
@biplobice 

Fixed
Please confirm

2022-02-22 02:52 UTC, biplobice commented
It would be great if you can make the filtering UI like this-
![Screen Shot 2022-02-22 at 11 50 50 AM](https://user-images.githubusercontent.com/2462951/155054270-2ade2a03-8313-469c-a3af-b26fa036a1be.png)

2022-02-22 03:29 UTC, biplobice requested changes
@Hmone23 
Your code is working fine but I've added some comments to standardize your code.
It would be great if you can adopt these and apply them in the future as well.
PhpStorm has lots of built-in features and plugins. Try to use & satisfy them.
If you need any help you may check https://biplobice.github.io/developers-mac/ or ask us.

2022-02-22 03:29 UTC, biplobice commented on single_pages/dashboard/ratings/view.php
> +                        }
- Make the text `unknown` translatable & Capitalize.
- Use proper spacing in your code. You may use `c5:phpcs` command. Or set it to your IDE https://biplobice.github.io/developers-mac/#/?id=install-php-cs-fixer

2022-02-22 03:29 UTC, biplobice commented on controllers/single_page/dashboard/ratings.php
> +        }
IMO, the `if ($results)` check is unnecessary. You could already set the variables.

2022-02-22 03:29 UTC, biplobice commented on controllers/single_page/dashboard/ratings.php
> +                'Content-Disposition' => 'attachment; filename=ratings_history_' . Carbon::now() . '.csv',
As you have changed the page name. IMO, it's better to change the CSV filename as well.

2022-02-22 03:29 UTC, biplobice commented on controllers/single_page/dashboard/ratings.php
> +    }
Wrong code design.
By the name `getFilterByRatedDate` I assume you're trying to get a filter object which isn't.
You may try this approach https://github.com/concrete5/concrete5/blob/8.5.x/concrete/controllers/single_page/dashboard/reports/logs.php#L161-L194

2022-02-22 03:29 UTC, biplobice commented on src/Export/ExportRatings.php
> +class ExportRatings
It would be great if you can rename the class to `RatingExporter` and follow this coding https://github.com/concrete5/concrete5/blob/8.5.x/concrete/src/Csv/Export/UserExporter.php

BTW, if you don't know how to refactor a class using PhpStorm https://www.jetbrains.com/help/phpstorm/refactoring-source-code.html

2022-02-24 08:29 UTC, Hmone23 commented
@biplobice 

Thank for your comments.
Fixed

2022-02-24 11:12 UTC, biplobice commented on controllers/single_page/dashboard/ratings.php
> +    }
`getFilterByRatedDate ` makes me feel like you're trying to get a filter object. 
If I'm not wrong the reference I sent you has `getFilteredList` which clearly states that you're trying to get a list object which is filtered.

2022-02-24 11:13 UTC, biplobice commented on single_pages/dashboard/ratings/view.php
> +                        <th class="<?=$ratingsList->getSortClassName('r.ratedAt')?>"><a href="<?=$ratingsList->getSortURL('r.ratedAt')?>">ratedAt</a></th>
Should be `Rated At` instead of `ratedAt`

2022-02-24 11:14 UTC, biplobice commented on single_pages/dashboard/ratings/view.php
> +                        }
> Use proper spacing in your code.

Haven't done yet.

2022-02-24 11:15 UTC, biplobice commented on single_pages/dashboard/ratings/view.php
> +                            <td><?=h($page->getCollectionName())?></td>
Not fixed yet.

2022-02-24 11:16 UTC, biplobice commented on src/Export/ExportRatings.php
> +class ExportRatings
Not done yet.
If you don't want to change the class name you should tell us. Perhaps, explain why.

2022-02-24 11:19 UTC, biplobice commented on src/Export/ExportRatings.php
> +            $name = 'unknown';
You should keep the text similar.

2022-02-25 01:08 UTC, Hmone23 commented on single_pages/dashboard/ratings/view.php
> +                        $name = t('Unknown');
@biplobice 

I have fixed it.

2022-02-25 01:09 UTC, Hmone23 commented on single_pages/dashboard/ratings/view.php
> +                        }
> > Use proper spacing in your code.
> 
> Haven't done yet.

I have fixed it.
Please confirm

2022-02-25 01:12 UTC, Hmone23 commented on controllers/single_page/dashboard/ratings.php
> +    }
> `getFilterByRatedDate ` makes me feel like you're trying to get a filter object.
> If I'm not wrong the reference I sent you has `getFilteredList` which clearly states that you're trying to get a list object which is filtered.

Yes, I fixed it according your reference code.
https://github.com/concrete5cojp/c5j_ratings/blob/feature/Dashboard_Report/controllers/single_page/dashboard/ratings.php#L78-L90

2022-02-25 01:20 UTC, Hmone23 commented on src/Export/ExportRatings.php
> +class ExportRatings
> Not done yet.
> If you don't want to change the class name you should tell us. Perhaps, explain why.

Sorry, I forgot to commit this file.

2022-02-25 01:27 UTC, Hmone23 commented on src/Export/ExportRatings.php
> +            $name = 'unknown';
> You should keep the text similar.

I fixed it.
Please confirm.

2022-02-25 03:26 UTC, biplobice commented on controllers/single_page/dashboard/ratings.php
> +    }
I wanted you to change the method name to `getFilteredList` as you're getting the list object not the filter object.

2022-02-25 03:31 UTC, biplobice commented on single_pages/dashboard/ratings/view.php
> +                        }
Sorry, I think I couldn't explain you.
Please check this documentation https://www.php-fig.org/psr/psr-2/
You don't use proper spacing on an if condition.
You can fix those at once by using the `c5:phpcs` command or setting external tools to the PhpStorm. See https://cs.symfony.com/

2022-02-25 03:32 UTC, Hmone23 commented on controllers/single_page/dashboard/ratings.php
> +    }
> I wanted you to change the method name to `getFilteredList` as you're getting the list object not the filter object.

Sorry, I fixed it.

2022-02-25 03:41 UTC, Hmone23 commented on single_pages/dashboard/ratings/view.php
> +                        }
> Sorry, I think I couldn't explain you.
> Please check this documentation https://www.php-fig.org/psr/psr-2/
> You don't use proper spacing on an if condition.
> You can fix those at once by using the `c5:phpcs` command or setting external tools to the PhpStorm. See https://cs.symfony.com/

Yes, I ran it using ` concrete/bin/concrete5 c5:phpcs fix packages/c5j_ratings`
but it didn't change
<img width="1416" alt="Screen Shot 2022-02-25 at 12 38 29 PM" src="https://user-images.githubusercontent.com/43093665/155649371-0ed52009-fc89-447b-854a-04772fe4f33c.png">

2022-02-25 08:38 UTC, biplobice commented on single_pages/dashboard/ratings/view.php
> +                        }
https://www.php-fig.org/psr/psr-2/#51-if-elseif-else
This is how to write an if-else condition.
The `phpcs` command should fix these. If it doesn't you may want to make an issue on `concrete5` repo.
Anyway, I'm gonna fix this for you.

2022-02-25 09:17 UTC, biplobice commented
@Hmone23 
It looks much better now.
I would like to request you a couple of more improvements.

1. The search box and the table has different date format. Please use the same.
   Hint: Check core, don't use any custom format as the format will be different based on language or timezone.
2. Search result includes results other than the specified one.

![Screen Shot 2022-02-25 at 5 54 48 PM](https://user-images.githubusercontent.com/2462951/155685616-1af46369-06a1-4beb-a6df-249ab15c3354.png)

2022-02-25 09:34 UTC, Hmone23 commented
@biplobice 

> Search result includes results other than the specified one.

 Search result includes results other than the specified one because `createdAt` field is date time format.
it will search from the searched date.

```
 public function filterByRatedDate($date, $comparison = '>=')
    {
        $this->query->andWhere($this->query->expr()->GTE('r.ratedAt', ':date'));
        $this->query->setParameter('date', $date);
    }
```
<img width="1290" alt="Screen Shot 2022-02-25 at 6 28 23 PM" src="https://user-images.githubusercontent.com/43093665/155691363-42d2eeb0-176f-48c8-9ab7-a4fab83bb74b.png">

2022-02-25 09:51 UTC, Hmone23 commented
@biplobice 

> The search box and the table has different date format. Please use the same.
> Hint: Check core, don't use any custom format as the format will be different based on language or timezone.

thank for hint. Fixed

2022-02-25 10:29 UTC, biplobice commented
> it will search from the searched date.

Well, you should use `Rated After` (exclusive, ratedAt > ratedAfter) or `Rated From` (inclusive, , ratedAt >= ratedFrom) then.

Also, FYI, core uses placeholder instead of a label.

**TLDR; Remove `Rated Date` label from on top of the search box and add the placeholder `Rated From`.**

2022-02-28 01:02 UTC, Hmone23 commented
@biplobice 

> Also, FYI, core uses placeholder instead of a label.
> TLDR; Remove Rated Date label from on top of the search box and add the placeholder Rated From.

I don't know how to use placeholders in the core date picker.
Please tell me how to fix.

2022-02-28 01:14 UTC, biplobice commented
Hmm, there is no such an option to add a placeholder in core.
You may add a piece of javascript code-
```
<script>
    $('#rated_date_pub').attr('Placeholder', "<?= t('Rated From') ?>");
</script>
```

2022-02-28 01:48 UTC, Hmone23 commented
@biplobice 

Thanks
Fixed

2022-02-28 02:16 UTC, biplobice commented
@Hmone23 
Oops! Sorry!
Please update the changelog.
It should be `### Added` not `### Fixed`

2022-02-28 02:20 UTC, merged